### ISSUE TITLE
Add story marker

### ISSUE THREAD

**Issue by yus252** [instedd/oasis#161]
The map should show the user all the stories (saved in Story table in database). Need to:

- [x] Get all the my_stories and corresponding info, such as gender, sex, sick, tested and so on from Story table. (Database) 
- [x] Get the coordinate of the city's center + a random distance from the center of the city(Mapbox Reverse Geocoding)
- [x] Add a marker for each story with the text to the map(Mapbox Marker)
- [x] Style the story popups.

**Comment by alex-wenzel** [comment]
Just for the record, the issue says "edited by alex-wenzel" because I accidentally checked one of the todo boxes - that was the only change. Apologies.

**Comment by yus252** [comment]
Need to change the map on every page except the dashboard page into background image @ste519

**Comment by yus252** [comment]
Current code allows user to see all the stories on the map with the corresponding color legend. Need to:

- [ ] Differentiate current user's marker and other users' marker 
- [ ] Add water/land marker checker and regenerate geocode
- [ ] Add dashboard for legend

**Comment by yus252** [comment]
Need to fix some issues of the Map.
